### ISSUE TITLE
Status not parsing correctly 

### ISSUE THREAD

**Issue by jjdd12** [edin-m/node-vagrant#18]
Attempting to get the status of a machine returns an empty object
```
import { Machine } from 'node-vagrant';
new Machine({cwd:'C:\\Users\\Me\\vagrant'});
machine.status((err, res) =>
{
 console.log(err);
 console.log(res)
})
```

results in 
>null
>{}

running the command manually 

`C:\Users\Me\vagrant>vagrant status`

results in
```
All Plugin Dependencies already installed
Current machine states:

dev_machine_2            running (virtualbox)

The VM is running. To stop this VM, you can run `vagrant halt` to
shut it down forcefully, or you can run `vagrant suspend` to simply
suspend the virtual machine. In either case, to restart it again,
simply run `vagrant up`.

```

**Comment by edin-m** [comment]
Let me know if it looks good and I'll publish it.

**Comment by jjdd12** [comment]
That looks good, however since the function is meant to get the status of a single instance, would be possible for it to return a single "status" object instead of an array?

**Comment by jjdd12** [comment]
It Looks good, Thanks a bunch!
