### ISSUE TITLE
command doesn't handle spawn's on error event

### ISSUE THREAD

**Issue by adamtec** [edin-m/node-vagrant#22]
In command.js, runCommand should listen for child.on('error', cb) for cases where spawn fails not necessarily the actual process.

**Comment by edin-m** [comment]
That makes sense.

[ ] Should be improved

**Comment by edin-m** [comment]
The right way to do this seems to be to export spawned child from every command. For places where there is a custom emitter, this can be done by merging multiple event emitters (child's + custom) using events-merge package. I've pushed WIP on fix-22 branch (example: boxUpdate).
