### ISSUE TITLE
Ocassional box list error

### ISSUE THREAD

**Issue by Stieneee** [edin-m/node-vagrant#23]
I have been getting an occasional parser error. I have seen it happen for both long and short running processes.

I'm wondering if occasionally vagrant is spitting out something unexpected. I believe this started after I upgraded vagrant.

Anyone else experienced this issue?

I'm instrumenting the code to try and understand what is happening but I don't have a method of reproducing the error at the moment.

Vagrant: 2.0.4
node-vagrant: 1.3.3

```
/home/stieneee/git/runner/node_modules/node-vagrant/src/parsers.js:165
                box[key] = out.match(BOX_LIST_MATCHERS[key])[0];
                                                            ^

TypeError: Cannot read property '0' of null
    at /home/stieneee/git/runner/node_modules/node-vagrant/src/parsers.js:165:61
    at Array.map (<anonymous>)
    at Object.boxListParser (/home/stieneee/git/runner/node_modules/node-vagrant/src/parsers.js:162:10)
    at /home/stieneee/git/runner/node_modules/node-vagrant/src/index.js:73:26
    at ChildProcess.<anonymous> (/home/stieneee/git/runner/node_modules/node-vagrant/src/command.js:66:20)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by edin-m** [comment]
What do you get on: `vagrant box list`:

**Comment by Stieneee** [comment]
```
laravel/homestead   (virtualbox, 2.2.0)
ubuntu/trusty64     (virtualbox, 20170818.0.0)
```
Exactly what I expect.

#24 Looking at your pr that definitely could be the problem nice catch. I have added an additional log to a local based I will let my application run over the weekend to see the issue is based on the new message.

Do you know if vagrant's new version message is periodic?

**Comment by edin-m** [comment]
Think it's constant:
https://github.com/hashicorp/vagrant/blob/f3c5e86f28c90165e70a5dcc043576586b79b288/lib/vagrant/cli.rb#L49
https://github.com/hashicorp/vagrant/blob/0872609b591052ceac395981a2b0b1fb5c44d265/lib/vagrant/util/checkpoint_client.rb#L114

Let's try PR #24 for now, and if box update messages start to appear, this can be used:
https://github.com/hashicorp/vagrant/commit/4d9717ae4c8fdf269ae618b895c7abbb7580866b
to disable box update check.
