### ISSUE TITLE
Stream instead of callback

### ISSUE THREAD

**Issue by absalomedia** [edin-m/node-vagrant#27]
Is there any way to provide responses as streams instead of callbacks?

I've just been expanding logging functionality based on user feedback here: https://github.com/absalomedia/vagrant-manager/issues/10 & they would prefer the output from each machine command to be streamed instead of being a callback.

**Comment by edin-m** [comment]
Not with the current state. Except for the `box add` `box update` and `up` commands which are not stdout and stderr outputs anyway.
This can easily be done for the machine set of commands by passing in stdout and stderr emit wrapper for the machine to the `runCommand`. Little more work for other vagrant commands (e.g. `box <>`) but still can be done by making them return EventEmitter.
Are the `stdout` and `stderr` outputs through events good enough for you?

**Comment by absalomedia** [comment]
Yes, they are. Only need them at machine level for moment.

**Comment by edin-m** [comment]
I've put up a PR related to this issue. Can you go over it and see if it needs anything else?

**Comment by absalomedia** [comment]
I’ve had a look & it looks fine to me
