### ISSUE TITLE
Updating boxes dynamically

### ISSUE THREAD

**Issue by absalomedia** [edin-m/node-vagrant#29]
Looking at the boxUpdate code, I note you specify both box & provider need to be supplied. 

In order for me to complete automated [box updating](https://github.com/absalomedia/vagrant-manager/issues/13), I need a way to run the Vagrant box update task without the provider set. I can capture the name fine.

The only other solution would be to pass the box provider through the boxListOutdatedParser so I can use it?

**Comment by edin-m** [comment]
I think automatically assigning the default provider if the provider string is empty should work well.

**Comment by absalomedia** [comment]
Your solution works well. Thanks for this
