### ISSUE TITLE
Add typing file for package

### ISSUE THREAD

**Issue by MasterOdin** [edin-m/node-vagrant#34]
I've been playing around with this library in a personal typescript project and having to build up a typing file for this package. Would you prefer that such a typing package be provided within this package or published to the [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) metapackage?

**Comment by edin-m** [comment]
"a typing package be provided within this package"

Is that a single file or...? I'm not familiar with `DefinitelyTyped`.

**Comment by MasterOdin** [comment]
So it would be minimally four files that would probably be put into a `typing` folder in this repo or DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package):
* index.d.ts: Contains the typings that describe node-vagrant
* node-vagrant-test.ts: Contains a test file to ensure correctness of the typings
* tsconfig.json: File to allow compiling the above .ts files
* tslint.json: Allow linting the above .ts files

If this was added here, then package.json file additionally then gets modified to have a new entry `"types": "typing/index.d.ts"`. If this is under DefinitelyTyped, no changes happen here.

For reference, [handlebars.js](https://github.com/wycats/handlebars.js) is an example of a library that includes the typings in their own repo, and then there's plenty of libraries who do not have typings included and are done by the community (hopefully) in [DefinitelyTyped] (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types).

**Comment by edin-m** [comment]
I don't have a preference when it comes to this since it's an unknown for me. I'm fine with whatever is the recommended way. I'm assuming it's recommended to have this info along within the package itself. 

In that case, I don't have objections merging a PR for this.

**Comment by MasterOdin** [comment]
Given your comments, I think it'd be better to go with DefinitelyTyped so as to have the types and updating them be independent of the module version here as I'm not sure you'd keep it up to-date with any changes that you make. Opened PR there (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37905).
