### ISSUE TITLE
Compatibility issue with new Windows 10 Terminal

### ISSUE THREAD

**Issue by absalomedia** [edin-m/node-vagrant#38]
Node Vagrant needs to be compatible with the coming release of Windows 10 Terminal (release 2020).

Otherwise you lose platform compatibility, as seen in errror thrown here: https://github.com/absalomedia/vagrant-manager/issues/21

**Comment by edin-m** [comment]
Can't figure out the root cause... If I understand correctly it's: a) node's spawn b) PowerShell exe name and/or version c) Windows .NET dependencies?

**Comment by absalomedia** [comment]
Would it be further up the line than your work? Inside Vagrant itself? Considering it's the thing trying to detect Powershell version?

**Comment by edin-m** [comment]
Yeah, this is something upstream probably. This lib is calling nodejs child_process, and from I can see in the screenshots, it may be something to do with the nodejs child_process side.
