### ISSUE TITLE
Create a machine instance from a vagrant id

### ISSUE THREAD

**Issue by angelxmoreno** [edin-m/node-vagrant#4]
How can I create a machine instance by a given vagrant machine id? I am looking to do something like this:

```js
var vagrant = require('node-vagrant');
vagrant.globalStatus(function(err, boxes){
        var machines = [];
        boxes.forEach(function(box){
                var machine = vagrant.open(box.id);//something like this
                machines.push(machine);
        });
});
```

**Comment by edin-m** [comment]
There is no such capability at the moment.

Workaround is to get path to Vagrantfile with ```vagrant.globalStauts``` and use ```var machine = vagrant.create({ cwd: <path-to-existing-vagrantfile>})```

*NOTE: you must be careful not to init machine at this moment because it will overwrite your existing Vagrantfile

Other then that, you can use ```node-vagrant``` as usual: ```machine.status(console.log)```
