### ISSUE TITLE
How to set the provisioning?

### ISSUE THREAD

**Issue by ilbonte** [edin-m/node-vagrant#7]
I saw that provisoning has been implemented but I don't understand how to use it.
How can I do the equivalent of 

``` 
config.vm.provision "shell", inline: <<-SHELL

    sudo apt-get -y update

    sudo apt-get -y install git nodejs

    git clone <MY REPO HERE>

SHELL
```

Thank you :)

**Comment by edin-m** [comment]
Oh sorry, docs aren't catching up. Take a look at [example1.config.json](https://github.com/edin-m/node-vagrant/blob/master/test/example1.config.json). You can use ```shell``` provisioner with path attribute. There can be one type of provisioner (key value) and basically config key value pair is mapped onto Vagrantfile [here](https://github.com/edin-m/node-vagrant/blob/master/templates/basic.tpl#L33).

**Comment by ilbonte** [comment]
Thanks a million, now it's clear!
