### ISSUE TITLE
Provisioning with docker doesn't work

### ISSUE THREAD

**Issue by ilbonte** [edin-m/node-vagrant#9]
Hi, if you take the [Vagrant file from the test folder](https://github.com/edin-m/node-vagrant/blob/master/test/example1.Vagrantfile) and you run `vagrant up` it will not work and you'll get this error: ` VagrantPlugins::DockerProvisioner::Config:
 The following settings shouldn't exist: pull_images
`
You will get the same error if you run this code:

```javascript
var vagrant = require ('node-vagrant');

var machine = vagrant.create({
    cwd: process.cwd(),
    env: process.env
});

var config = {
    "config": {
        "vm": {
            "box": "ubuntu/trusty64"
        },

        "provisioners": {
            "docker": {
                "pull_images ": "\"ubuntu\""
            }
        }
    }
};

function onInit(err, out) {
    if (err) throw new Error(err);

    machine.up(function(err, out) {
        if (err) throw new Error(err);
        console.log('machine is up!');
        fs.unlinkSync('./Vagrantfile');
    });
}


machine.init('ubuntu/trusty64', config, onInit);

```

**I think that the problem** is that the[ template puts](https://github.com/edin-m/node-vagrant/blob/master/templates/basic.tpl#L36) a `=` in the Vagrantfile for every provisioners but in this case there should't be... For an example of the syntax scroll down to "BUILDING IMAGES": https://www.vagrantup.com/docs/provisioning/docker.html (I know, different syntax for every provider: sometimes there is "=", sometimes ":" and sometime nothing)

In fact if you edit the Vagrantfile produced from the code above removing the "=" between `docker.pull_images ` and `"ubuntu"` it works!

If you want to try by yourself this is the vagrantfile generated by node-vagrant. To get it work you need to remove the `=` :
```
Vagrant.configure(2) do |config|

  # https://docs.vagrantup.com.

 
  config.vm.box = "ubuntu/trusty64"
  
  
  config.vm.provision "docker" do |docker|
    
    docker.pull_images  = "ubuntu"
    
  end
  
end
```

**Comment by edin-m** [comment]
[True Dat](http://s2.quickmeme.com/img/78/78ef46ca312c706e1b2d243e9ee0d2a9d4ae644d7c6614210d5067163530da9f.jpg) Provisioners should have its own adapters. I've created [WIP](https://github.com/edin-m/node-vagrant/tree/feature/provision-adapters) and it works for docker use case but it should be considered other options like ```images: ['ubuntu']``` and other stuff.

**Comment by ilbonte** [comment]
Yes, for now I'm only using docker and shell as provisioner so I have edited the config to suit my needs but I wanted to let other people know because it took me a while to find the problem :innocent: 

If you want you can close the issue

**Comment by edin-m** [comment]
This config should make sense and could be copied to other settings as well.
```
        var provisionerConfig = {
            name: 'docker1',
            type: 'docker',
            config: {
                commands: [
                    'pull_images "ubuntu"',
                    'pull_images "ubuntu"',
                    'run "rabbitmq"',
                    'run "ubuntu", cmd: "bash -l", args: "-v \'/vagrant:/var/www\'"',
                    'run "db-1", image: "user/mysql"',
                    'images: ["ubuntu", "gentoo"]'
                ]
            }
        };
```

**Comment by edin-m** [comment]
[This](https://github.com/edin-m/node-vagrant/blob/feature/provision-adapters/test/example2.config.json#L43) is new example of config. Difference is provisioners are configured using array of ```{ name: '', type: '', config: { commands: [] } }``` objects. Seems like this is most flexible way and could be transferred to other configurations. Example of  [output Vagrantfile](https://github.com/edin-m/node-vagrant/blob/feature/provision-adapters/test/example2.Vagrantfile). I haven't tried it myself but I just know line with images array is invalid, and will be moved outside of commands list.

**Comment by ilbonte** [comment]
Will try it ASAP and let you know if I find any problem!
